### ISSUE TITLE
Dynamic Route for Code showcasing 

### ISSUE THREAD

**Issue by SikandarJODD** [max-got/originui-svelte#21]
Right now : Code looks like this : 
![image](https://github.com/user-attachments/assets/02f6bd58-d4c1-4af8-b91b-91ef1bbe3ae4)
- This dosen't look good for developers to view code 
- can i contribute on this 
### Proposal  
- Make Dynamic Route for components showcasing 
- Will be easier to look at code 
Future Preview : 
![image](https://github.com/user-attachments/assets/55561fbf-2af3-4fcd-bc79-eab024ce3d18)

we can have a sidebar consist of component names - and can showcase preview components and code on right side 
what are your thoughts ?

**Comment by SikandarJODD** [comment]
we need to add : 
- unique names, id  to each components to render dynamic page simple 
- will take some time to build - i feel it would be worth it for future usage to see the code and components 
checkout : [Svelte Animations](https://animation-svelte.vercel.app/luxe/dock-menu)

**Comment by max-got** [comment]
First of all, thank you for the first issue!

I am not really a fan of the sidebar approach, i want to keep this repo as close as possible to the original (even tho they don't have a code preview yet).

<hr>

> unique names, id to each components to render dynamic page simple

We already have that. Every Component is available in the api routes e.g.[/api/v1/components/buttons.json](https://originui-svelte.pages.dev/api/v1/components/buttons.json)
<hr>

I want to make use of Kits [Shallow Routing](https://svelte.dev/docs/kit/shallow-routing) as i don't want to simply copy Origin UI, i want to showcase Svelte/Kits capabilities as well. I made a little something at #23 (only buttons route for now). Maybe you can work with that approach.
The problem for now is, that the component gets asynchronously rendered on shallow routing, even tho it is already rendered. If you have a better (and most importantly better perfomant approach), feel free to create something!  I am totally open to ideas. But as i said, try to keep it as close as possible to the original 👍

**Comment by SikandarJODD** [comment]
Great i will try out 2 approch : 
1. Shallow routing 
2. we showcase components inside modals like after clicking on code we can show modal 
Modal will include 
- component preview 
- code 
- prev and next 
Will try both  approch n let you know

**Comment by SikandarJODD** [comment]
i have made a lot of changes : 
- installed shadcn, updated bits ui -- so it's better you can copy this file 
imp code : 

- added dialog component from shadcn - svelte 5 
- ```demo-dialog.svelte``` : [Demo Dialog Code](https://github.com/SikandarJODD/originui-svelte/blob/main/src/lib/demo/demo-component/demo-dialog.svelte)
- minor changes in ```demo-component``` [Code](https://github.com/SikandarJODD/originui-svelte/blob/main/src/lib/demo/demo-component/demo-component.svelte)

### Minor changes in Inputs, Buttons, Radio boxes... ```+page.svelte```
```
<DemoComponents.Demo {component} allcomponents={data.inputComponents} />
```
- added ```allcomponents`` in all three +page.svelte - useful for modal to render
